.github/workflows/lint.yml, .github/workflows/validate.yml
We don't use them, and don't have the secret available on a public repo.
=> ci: Remove submodule read

services/gcp/cloudfunctions/functions.yml, services/gcp/pubsub/topics.yml
Remove cloudfunctions takeover vulns since they require iam.serviceAccounts.actAs to execute
=> Remove cloudfunctions takeover vulnerabilities and explain pubsub topic deletion vulnerability

risks/destruction/infra.yml, risks/destruction/network.yml
We're moving DOS-type risks away from CRITICAL for better prioritization. In keeping with this, move infra + network deletion risks to HIGH.
Note that we should explicitly label deletion of infrastructure that holds data with destruction:data to keep its criticality.
=> risks: Move infra / network deletion to HIGH

services/gcp/compute/instances.yml
Added explanation for why compute.instances.stop privilege leads to data destruction with explanation and reference to the documentation.
=> Add explanation and reference for compute.instance.stop data:destruction

services/gcp/container/daemonSets.yml, services/gcp/container/deployments.yml, services/gcp/container/jobs.yml, services/gcp/container/pods.yml, services/gcp/container/replicaSets.yml, services/gcp/container/statefulSets.yml
These permissions allow only the deletion of ephemeral volumes, which typically do not store data that users would associate with a data destruction risk. Persistent volumes are retained. This was already explained in the notes.
=> Remove destruction:data risk from GCloud container update and delete operations

services/gcp/iam/serviceAccounts.yml
Adds some additional insight into token lifetime.
=> gcp: Annotate iam.serviceAccounts.getAccessToken

risks/exfiltration/crypto.yml, services/gcp/container/secrets.yml, services/gcp/secretmanager/locations.yml, services/gcp/secretmanager/versions.yml
Unify secrets exploits behind exfiltration:crypto (which implies account escalation already when crypto material is an account key).
=> secrets: Fix risks

services/gcp/bigquery/connections.yml
Google (per their docs) explicitly excludes SQL creds from returned metadata.
=> gcp: Fix bq.connections.get

services/gcp/compute/instances.yml
Not an account takeover as:
- the token is short-lived
- the caller must already be able to act as the account
=> gcp: Remove compute.instances.create account takeover

risks/destruction/artifact.yml, services/gcp/bigquery/models.yml
replace risks of destruction infra, data with artifact as original data is not deleted.
Adds destruction of artifacts
=> Updated risks for bigquery.models.updateMetadata 

services/gcp/container/clusterRoleBindings.yml, services/gcp/container/clusterRoles.yml, services/gcp/container/roleBindings.yml, services/gcp/container/roles.yml, services/gcp/container/serviceAccounts.yml
Removes escalation:privilege permissions from role/clusterRole and roleBinding/clusterRoleBinding create and update permissions since additional conditions must be satisfied that mitigate escalation risk.
=> Remove escalation:privilege from container permissions

services/gcp/recommender/iamPolicyRecommendations.yml
`iamPolicyRecommendations.yaml` should refer to IAM Policy Recommendations permissions
=> Fix typo in IAM Policy Recommendations permissions

cspell.json, services/gcp/compute/instances.yml, services/gcp/dataproc/clusters.yml
Adds an important service-account takeover path from https://www.blackhat.com/us-20/briefings/schedule/#lateral-movement-and-privilege-escalation-in-gcp-compromise-any-organization-without-dropping-an-implant-19435.
Also remove duplicate risk in compute.instances.create.
=> dataproc: Add clusters

services/gcp/bigquery/connections.yml, services/gcp/cloudbuild/builds.yml, services/gcp/container/clusterRoles.yml, services/gcp/container/roles.yml, services/gcp/container/serviceAccounts.yml, services/gcp/iam/roles.yml, services/gcp/iam/serviceAccountKeys.yml, services/gcp/iam/serviceAccounts.yml, services/gcp/pubsub/topics.yml
The principle behind this review:
- `escalation:privilege` allows users to access more sensitive permissions within the same service
- `escalation:lateral` allows users to gain access to new services. This is typically via service account impersonation, either direct or indirect (e.g. CloudBuild)
The net result is that some permissions are re-categorized from `escalation:privilege` to `escalation:lateral`, and some permission gained `escalation:lateral` to have both.
=> Review "escalation:privilege" and "escalation:lateral" risks

services/gcp/apikeys/keys.yml, services/gcp/compute/images.yml
While validating basic roles, I noticed:
- viewer had crypto exfil, which I doubted, so I checked the API response for the compute images get/list methods, and it does not include the raw key. it only includes a sha256 hash of the key. (response included below)
- apikeys sounded sensitive and was in the no risks section, so I added it
Image API response 
```
{
"kind": "compute#imageList",
"id": "projects/still-girder-340817/global/images",
"items": [
{
"kind": "compute#image",
"id": "1190729280232419561",
"creationTimestamp": "2023-11-03T12:46:15.205-07:00",
"name": "image-1",
"sourceType": "RAW",
"status": "PENDING",
"diskSizeGb": "10",
"sourceDisk": "https://www.googleapis.com/compute/v1/projects/still-girder-340817/zones/us-central1-a/disks/permz-test-instance-1",
"sourceDiskId": …
```
=> Privilege updates while validating basic roles

services/gcp/datastore/namespaces.yml
BOOST is a risk score, not a scope score. Set to the correct value (LOW).
Fixes #89.
=> gcp/datastore: Fix namespaces scope

.github/workflows/cd.yml
Adds the p0-catalog project to the deploy pipeline. A follow-up will remove the other project once we switched our services to read from the new project.
=> Add catalog project to deploy pipeline

.github/workflows/cd.yml, services/README.md, services/gcp/compute/instances.yml, services/gcp/container/secrets.yml
Replace `--auto-detect` with `--ignore_unknown_values` when loading BQ.
This change works with a predefined BigQuery table schema because it does not replace the already existing schema. The existing `--replace` flag in this case only replaces the data, not the schema. The `--ignore_unknown_values` flag makes the load more resilient against deviations from the table schema.
Also: two privileges contain mitigations: `services/gcp/compute/instances.yml` and `services/gcp/container/secrets.yml`, however the former uses a string `mitigation` field while the latter uses an array `mitigations` field. Settle on the singular form to avoid a conflict with the `mitigations` field of risks, which is also loaded into BQ.
=> CD: load BigQuery without --auto-detect

.github/workflows/cd.yml, scripts/generate.ts, services/workspace/admin.yml, services/workspace/groups.yml, services/workspace/organization_units.yml, services/workspace/users.yml
This provides risks for the Groups Admin role.
Also removes some duplication from the CD script, which simplifies adding CD for Workspace risks.
=> workspace: Add initial catalog

.github/workflows/cd.yml
This was left when refactoring the per-service CD logic. And a good reason to deduplicate logic.
=> cd: Fix typo

.github/workflows/cd.yml
Variable expansion requires an `echo` to unpack a space-delimited string,
apparently.
=> cd: Fix upload script

services/gcp/run/jobs.yml
References: https://cloud.hacktricks.wiki/en/pentesting-cloud/gcp-security/gcp-privilege-escalation/gcp-run-privesc.html
Also see this discussion: https://github.com/p0-security/app/pull/3028#pullrequestreview-2638922237
=> Add lateral escalation to some Cloud Run permissions
